#!/bin/sh
# Xcode Cloud starts this hook in ci_scripts, not the repository root.
set -eu
: "${CI_PRIMARY_REPOSITORY_PATH:?Run this hook in Xcode Cloud}"
: "${CI_BUILD_NUMBER:?Xcode Cloud must assign a build number}"
: "${CI_XCODE_SCHEME:?Xcode Cloud must select a shared scheme}"
case "$CI_BUILD_NUMBER" in
    ''|*[!0-9]*|0*) echo "Invalid cloud build number" >&2; exit 1 ;;
esac
case "$CI_XCODE_SCHEME" in
    Local|Dev|Prod) ;;
    *) echo "Unsupported cloud scheme" >&2; exit 1 ;;
esac
config_dir="$CI_PRIMARY_REPOSITORY_PATH/Configurations"
if [ "$CI_XCODE_SCHEME" = Prod ]; then
    # Public client identity, not a credential. Reject missing or Dev identity.
    # Update this allowlist after a verified Prod foundation/client replacement.
    if [ "${PIPPIPGO_PROD_COGNITO_CLIENT_ID:-}" != 23sk8qfmpotjj40jbnl9tn33em ]; then
        echo "Set PIPPIPGO_PROD_COGNITO_CLIENT_ID to the verified Prod public client in the workflow." >&2
        exit 1
    fi
    printf '%s\n' '// Generated from the verified Prod workflow identity; public only.' \
        "PIPPIPGO_COGNITO_CLIENT_ID = $PIPPIPGO_PROD_COGNITO_CLIENT_ID" \
        > "$config_dir/ProdIdentity.xcconfig"
fi
printf '%s\n' '// Generated by Xcode Cloud; never commit.' \
    "CURRENT_PROJECT_VERSION = $CI_BUILD_NUMBER" > "$config_dir/CIOverrides.xcconfig"
echo "Prepared $CI_XCODE_SCHEME cloud build $CI_BUILD_NUMBER"
